# Model arguments
model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: float16 # Use float16 for reduced memory usage
bf16: false # Disable bf16
tf32: true
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Lora Arguments
# No LoRA is used here

# Training arguments
max_steps: 20
per_device_train_batch_size: 1
gradient_accumulation_steps: 2 # Reduce accumulation steps to save memory
gradient_checkpointing: false # Disable gradient checkpointing
gradient_checkpointing_kwargs:
 use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03
# GRPO specific parameters
beta: 0.001
max_prompt_length: 256
max_completion_length: 512 # Reduce completion length to save VRAM
num_generations: 2 # Reduce the number of generations
use_vllm: true
vllm_gpu_memory_utilization: 0.1 # Reduce GPU memory usage for vllm

# Logging arguments
logging_strategy: steps
logging_steps: 10 # Increase logging steps to reduce overhead
report_to:
 - tensorboard
save_strategy: 'steps'
save_steps: 50 # Increase save steps to reduce overhead
seed: 42

# Hugging Face Hub
# push_to_hub: false
# hub_strategy: every_save

# Script arguments
public_maddr: '/ip4/38.101.215.12/tcp/30002'
host_maddr: '/ip4/0.0.0.0/tcp/38331'
max_rounds: 10000
