# Model arguments
model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Lora Arguments
# No LoRA is used here

# Training arguments
max_steps: 1000 # You can scale this depending on your experiment length
per_device_train_batch_size: 2 # was 4
gradient_accumulation_steps: 16 # was 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
 use_reentrant: false
learning_rate: 1.0e-6 # Slightly higher for faster convergence (you can tune)
lr_scheduler_type: cosine
warmup_ratio: 0.03
beta: 0.001 # Keep as is
max_prompt_length: 256
max_completion_length: 512 # Reduce a bit to save memory, unless your use case requires 1024
num_generations: 4 # Reduce from 8 to save memory for vLLM
use_vllm: true
vllm_gpu_memory_utilization: 0.85 # Safe sweet spot for a 3090 with 17GB free
# vllm_device: "cuda:0"  # Optional to be explicit

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
 - tensorboard
save_strategy: 'steps'
save_steps: 100
seed: 42

# Hugging Face Hub
# push_to_hub: false
# hub_strategy: every_save

# Script arguments (Swarm / Gensyn)
public_maddr: '/ip4/38.101.215.12/tcp/30002'
host_maddr: '/ip4/0.0.0.0/tcp/38331'
max_rounds: 10000
